services:
    Mh\PageBundle\Command\:
        resource: '../../Command'
        arguments: ['@service_container', '@logger', '@security.user_password_encoder.generic']
        tags: ['console.command']

    Mh\PageBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Mh\PageBundle\EventSubscriber\:
        resource: '../../EventSubscriber'
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    Mh\PageBundle\Helper\:
        resource: '../../Helper'
        arguments: ['@service_container', '@logger']
        public: true

    Mh\PageBundle\Repository\:
        resource: '../../Repository'
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    Mh\PageBundle\Security\:
        resource: '../../Security'
        arguments: ['@doctrine.orm.default_entity_manager', '@router.default', '@security.csrf.token_manager', '@security.user_password_encoder.generic']
