services:
    Mh\PageBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Mh\PageBundle\Command\:
        resource: '../../Command'
        public: true
        tags: ['console.command']
        arguments: ['@service_container', '@logger']

    Mh\PageBundle\Helper\:
        resource: '../../Helper'
        public: true
        arguments: ['@service_container', '@logger']

    Mh\PageBundle\Repository\:
        resource: '../../Repository'
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']
