services:
    Mh\PageBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Mh\PageBundle\Repository\:
        resource: '../../Repository'
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

